# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: hyperdefined
url: "https://hyper.lol" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /post/:title

plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2

livereload: true

pagination:
  enabled: true
  per_page: 5
  permalink: '/page:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2
  collection: 'posts' 

reading_time:
  second_plural: "seconds"    # default: seconds
  minute_singular: "minute"  # default: minute
  minute_plural: "minutes"    # default: minutes

exclude:
  - build.*
  - LICENSE.txt
  - package.json
  - package-lock.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - scripts/