baseURL = 'https://hyper.lol/'
languageCode = 'en-us'
title = 'hyperdefined'
theme = 'hyperwolf'
defaultContentLanguage = "en"
[params]
    defaultDescription = "typing with paws is hard :3"
[permalinks]
  posts = '/:year/:month/:title/'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4    